version: '3.8'

services:
  frontend:
    build:
      context: ./front
      args:
        - REACT_APP_KEY=${REACT_APP_KEY}
    ports:
      - '3000:3000'
  
  backend:
    build:
      context: ./back
    ports:
      - '4000:4000'
    depends_on:
      - db2

  db2:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TFE_2023
      - POSTGRES_DB=TFE_2023
      
    ports:
      - '5432:5432'
    volumes:
      - ./back/init/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db2:/var/lib/postgresql/data 
    
   

volumes:
  db2:
    driver: local

