version: '3.8'

services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  frontend:
    build:
      context: ./front
      args:
        - REACT_APP_KEY=${REACT_APP_KEY}
    
    #environment:
    #  - BACKEND_HOST=http://localhost/api
    
  backend:
    build:
      context: ./back
    depends_on:
      - db2
    

  db2:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TFE_2023
      - POSTGRES_DB=TFE_2023
      
    volumes:
      - ./back/databaseFiles/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db2:/var/lib/postgresql/data 
    
    
   

volumes:
  db2:
    driver: local

